### ISSUE TITLE
Found a bug in XmlWriter

### ISSUE THREAD

**Issue by smstabber** [dom4j/dom4j#146]
1. new XMLWriter(new FileWriter(xmlFilePath),outputFormat)
2. new XMLWriter(new FileOutputStream(xmlFilePath), outputFormat)
In the above two constructors, the first one does not use the character encoding specified by outputformat, but uses the system environment encoding. The second uses outputformat encoding.
The first constructor that uses the filewriter parameter should be a bug.

**Comment by smstabber** [comment]
version 2.1.3

**Comment by ecki** [comment]
That’s not a bug, it is expected, if you specify a `Writer` it has to be configured with the desired encoding. The encoding argument to `XmlWriter` in this case only sets the character set declaration.

In order to allow the xml writer control over the written bytes you need to pass it a `OutputStream` or serialize to a byte[] array instead.
