### ISSUE TITLE
Resolve CVE-2023-45960

### ISSUE THREAD

**Issue by jwhance** [dom4j/dom4j#172]
CVE-2023-45960 is being reported against Dom4j.  Please resolve.

**Comment by ecki** [comment]
The POC of this CVE states it’s already fixed

**Comment by rahul-mb** [comment]
Dear @ecki , 
Could you please let me know when can we expect new release with fix for CVE-2023-45960 ? 
Thanks in advance!

**Comment by FilipJirsak** [comment]
CVE-2023-45960 is not an issue. There is nothing to fix it.

**Comment by ecki** [comment]
Well, if dom4j by default uses an unsecured parser and does not document it and does not provide a safe constructor, I would say there is some improvements to make (but not for the actual „sequence“ issue, since that is caused by old jaxp in JDK8 instead). Discussion over in the original repo indicates that the submitter will ask mitre to obsolete the issue.

**Comment by jwhance** [comment]
Unfortunately this is not resolved, but I closed this issue because there is another one on the subject.  There is a CVE, right or wrong, against dom4j and idiotic tools like Sonatype's Nexus, used by many companies including mine, are now blocking the library and anything that references it.  Yes, it's a problem!
