### ISSUE TITLE
Parsing XML string containing CDATA error

### ISSUE THREAD

**Issue by lifei636** [dom4j/dom4j#180]
XML string such as "<?xml version="1.0" encoding="UTF-8"?>\n<a><! [CDATA [\"<! [CDATA [2234]>\"]></a>";
Convert to XML; 
Document document=DocumentHelper. parseText (content); 
Error on line 1958 of document: The character sequence "]]>" cannot appear in the content unless it is used to mark the end of a CDATA section.

**Comment by FilipJirsak** [comment]
`dom4j` is not XML parser. It uses default `SAXParser` in `DocumentHelper.parseText()`. It calls:
```java
SAXReader.createDefault() 
```
By the way, the given input has no CDATA section - you have extra spaces after the exclamation point at the beginning, the correct start is `<![CDATA[`. There is no termination with `]]>` at the end. On the given input, the parser will not report the given error because the sequence `]]>` is nowhere there.
