### ISSUE TITLE
Add an automatic module name

### ISSUE THREAD

**Issue by carlosame** [dom4j/dom4j#67]
While I'm not an enthusiast of Java modularization, unfortunately Java libraries that aren't module-aware are increasingly being a source of compiler warnings as people migrate to newer JDKs.

It would help if dom4j set up an automatic module name in the Jar manifest, like:

`Automatic-Module-Name: org.dom4j`

I'm not familiar with gradle, but apparently the following would work:

```
jar {
  manifest {
    attributes('Automatic-Module-Name': 'org.dom4j')
  }
}
```

See https://guides.gradle.org/building-java-9-modules/#optional_add_code_automatic_module_name_code_manifest_entries_for_all_other_projects

Of course that a full `module-info` would also be a good thing, but the above solution is simple and solves the main issue of having to rely on generated module names.

**Comment by ColonelBlimp** [comment]
Can I up-vote this one :+1:

**Comment by carlosame** [comment]
This issue was marked for 2.1.2, but 2.1.2/2.1.3 went out without it so I prepared a [pull request](https://github.com/dom4j/dom4j/pull/84). It is tested and gives the desired result.

**Comment by reinhapa** [comment]
@FilipJirsak as a OpenJDK contributor I can definitively support this PR as it should be good practice to supply at least the `Automatic-Module-Name` in not jet modular libraries in order to have a stable library identification as explained [here](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/module/ModuleFinder.html#automatic-modules)
